// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_HAefMBLLvlsARLQ7DQ8bCUNhdoX9YT8',
    appId: '1:953206882212:web:b8ee7dcec4dbf760258b31',
    messagingSenderId: '953206882212',
    projectId: 'number-65099',
    authDomain: 'number-65099.firebaseapp.com',
    storageBucket: 'number-65099.firebasestorage.app',
    measurementId: 'G-64QC5820V9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAirlJVJF7OVoy7LIRjVd3oQCb2rCULEr8',
    appId: '1:953206882212:android:70efe760b775ac1b258b31',
    messagingSenderId: '953206882212',
    projectId: 'number-65099',
    storageBucket: 'number-65099.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjrLy193gQ6n_3C5ETRIrD8wJs3ACeitk',
    appId: '1:953206882212:ios:3e8ab650312f1f8c258b31',
    messagingSenderId: '953206882212',
    projectId: 'number-65099',
    storageBucket: 'number-65099.firebasestorage.app',
    iosBundleId: 'com.example.numberFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjrLy193gQ6n_3C5ETRIrD8wJs3ACeitk',
    appId: '1:953206882212:ios:3e8ab650312f1f8c258b31',
    messagingSenderId: '953206882212',
    projectId: 'number-65099',
    storageBucket: 'number-65099.firebasestorage.app',
    iosBundleId: 'com.example.numberFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_HAefMBLLvlsARLQ7DQ8bCUNhdoX9YT8',
    appId: '1:953206882212:web:5c256033f865eab9258b31',
    messagingSenderId: '953206882212',
    projectId: 'number-65099',
    authDomain: 'number-65099.firebaseapp.com',
    storageBucket: 'number-65099.firebasestorage.app',
    measurementId: 'G-F71WMGMFG7',
  );
}
